"""remove purpose column

Revision ID: 175416ee2978
Revises: 9ff778c76a76
Create Date: 2024-10-21 10:20:19.142457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175416ee2978'
down_revision: Union[str, None] = '9ff778c76a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
