"""rename seed type

Revision ID: 9ff778c76a76
Revises: c3bf6b1fa32b
Create Date: 2024-10-20 18:22:51.149619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff778c76a76'
down_revision: Union[str, None] = 'c3bf6b1fa32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('seed_type', sa.String(), nullable=True))
    op.drop_column('seeds', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('seeds', 'seed_type')
    # ### end Alembic commands ###
